server:  port: 8091  servlet:    context-path: /    
spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/dbsm?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: rootcourse:  name: 英语  hour: 30  credit: 5.0    
#spring整合Mybatis
mybatis:
    #配置别名包 
  #type-aliases-package: com.jt.pojo
    #加载mapper映射文件
  #mapper-locations: classpath:/mybatis/mappers/*.xml
    #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
#添加日出输出
#logging:
  #level:
   # com.jt.mapper: debug
  